In [2]:
import pandas as pd
from sklearn.preprocessing import OneHotEncoder , LabelEncoder , OrdinalEncoder
from sklearn.compose import ColumnTransformer
from sklearn.model_selection import train_test_split

In [3]:
df = pd.read_csv('AI_Student_Life_Pakistan_2026.csv')

In [6]:
df.head()

,Student_ID,Age,Gender,Education_Level,City,AI_Tool_Used,Daily_Usage_Hours,Purpose,Impact_on_Grades,Satisfaction_Level
0,1,15,Female,School,Lahore,ChatGPT,0.8,Writing,Slight Decline,Low
1,2,15,Female,College,Multan,Copilot,1.6,Learning,No Change,High
2,3,16,Female,College,Multan,ChatGPT,1.8,Research,Improved,Low
3,4,22,Male,University,Karachi,ChatGPT,4.2,Learning,Improved,High
4,5,16,Male,School,Multan,ChatGPT,1.8,Coding,Improved,Medium

In [7]:
x=df.drop('Satisfaction_Level' , axis=1)
y=df['Satisfaction_Level']

In [8]:
X_train,X_test,y_train,y_test = train_test_split(x,y ,test_size=0.2)

In [9]:
transformer = ColumnTransformer(transformers=[
    ('tnf1',OrdinalEncoder(categories=[['School','College','University'] , ['Slight Decline','No Change','Improved']]),['Education_Level','Impact_on_Grades']),
    ('tnf2',OneHotEncoder(sparse_output=False,drop='first'),['Gender','City','AI_Tool_Used','Purpose'])
],remainder='passthrough')
le = LabelEncoder()

In [10]:
transformer.fit_transform(X_train)
transformer.transform(X_test)

array([[ 2. ,  2. ,  0. ,  0. ,  0. ,  1. ,  0. ,  0. ,  0. ,  0. ,  1. ,
         0. ,  1. ,  0. ,  0. , 52. , 16. ,  0.7],
       [ 0. ,  2. ,  1. ,  1. ,  0. ,  0. ,  0. ,  0. ,  1. ,  0. ,  0. ,
         0. ,  0. ,  0. ,  0. , 47. , 23. ,  3.2],
       [ 1. ,  2. ,  0. ,  0. ,  0. ,  0. ,  1. ,  0. ,  0. ,  0. ,  0. ,
         1. ,  0. ,  0. ,  0. , 88. , 20. ,  3.3],
       [ 2. ,  1. ,  0. ,  0. ,  0. ,  0. ,  1. ,  0. ,  0. ,  0. ,  0. ,
         1. ,  0. ,  0. ,  0. , 26. , 16. ,  1.8],
       [ 2. ,  1. ,  1. ,  0. ,  1. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,
         1. ,  0. ,  0. ,  0. , 17. , 16. ,  0.7],
       [ 1. ,  1. ,  0. ,  1. ,  0. ,  0. ,  0. ,  1. ,  0. ,  0. ,  0. ,
         0. ,  0. ,  0. ,  1. , 91. , 16. ,  3.9],
       [ 0. ,  0. ,  0. ,  0. ,  1. ,  0. ,  0. ,  0. ,  0. ,  0. ,  1. ,
         0. ,  1. ,  0. ,  0. , 56. , 25. ,  2.2],
       [ 2. ,  2. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  1. ,
         0. ,  0. ,  1. ,  0. , 51. , 25. ,  1.9],
       [ 0. ,  1. ,  1. ,  0. ,  0. ,  0. ,  0. ,  1. ,  0. ,  0. ,  0. ,
         0. ,  0. ,  0. ,  0. , 28. , 20. ,  4.8],
       [ 2. ,  0. ,  0. ,  1. ,  0. ,  0. ,  0. ,  1. ,  0. ,  0. ,  0. ,
         0. ,  0. ,  1. ,  0. , 90. , 15. ,  1.9],
       [ 0. ,  0. ,  0. ,  0. ,  1. ,  0. ,  0. ,  0. ,  1. ,  0. ,  0. ,
         1. ,  0. ,  0. ,  0. , 43. , 25. ,  0.9],
       [ 0. ,  0. ,  1. ,  1. ,  0. ,  0. ,  0. ,  0. ,  0. ,  1. ,  0. ,
         0. ,  1. ,  0. ,  0. , 71. , 19. ,  3. ],
       [ 1. ,  1. ,  1. ,  0. ,  0. ,  0. ,  1. ,  0. ,  1. ,  0. ,  0. ,
         0. ,  0. ,  1. ,  0. , 65. , 23. ,  1.4],
       [ 0. ,  1. ,  0. ,  1. ,  0. ,  0. ,  0. ,  0. ,  0. ,  1. ,  0. ,
         0. ,  0. ,  1. ,  0. , 54. , 25. ,  2.5],
       [ 2. ,  2. ,  0. ,  0. ,  0. ,  1. ,  0. ,  0. ,  0. ,  1. ,  0. ,
         0. ,  1. ,  0. ,  0. , 92. , 16. ,  3. ],
       [ 0. ,  1. ,  0. ,  0. ,  0. ,  0. ,  1. ,  0. ,  0. ,  1. ,  0. ,
         0. ,  0. ,  1. ,  0. , 55. , 17. ,  1.9],
       [ 1. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  1. ,  0. ,  0. ,
         0. ,  0. ,  1. ,  0. , 32. , 16. ,  4. ],
       [ 0. ,  1. ,  1. ,  0. ,  1. ,  0. ,  0. ,  1. ,  0. ,  0. ,  0. ,
         0. ,  0. ,  0. ,  1. , 33. , 22. ,  1.8],
       [ 2. ,  2. ,  0. ,  0. ,  0. ,  1. ,  0. ,  0. ,  0. ,  0. ,  0. ,
         0. ,  1. ,  0. ,  0. , 81. , 25. ,  0.6],
       [ 0. ,  1. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  1. ,  0. ,  0. ,
         0. ,  0. ,  0. ,  1. , 97. , 25. ,  1.9]])

In [11]:
le.fit_transform(y_train)
le.transform(y_test)

array([2, 1, 1, 0, 2, 1, 0, 2, 1, 2, 2, 1, 1, 2, 2, 2, 1, 0, 2, 2])

In [12]:
pd.DataFrame(transformer.fit_transform(X_train) , columns=transformer.get_feature_names_out())

,tnf1__Education_Level,tnf1__Impact_on_Grades,tnf2__Gender_Male,tnf2__City_Islamabad,tnf2__City_Karachi,tnf2__City_Lahore,tnf2__City_Multan,tnf2__AI_Tool_Used_Copilot,tnf2__AI_Tool_Used_Gemini,tnf2__AI_Tool_Used_Grammarly,tnf2__AI_Tool_Used_Notion AI,tnf2__Purpose_Homework,tnf2__Purpose_Learning,tnf2__Purpose_Research,tnf2__Purpose_Writing,remainder__Student_ID,remainder__Age,remainder__Daily_Usage_Hours
0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,66.0,23.0,0.6
1,0.0,2.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,94.0,21.0,3.9
2,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,64.0,22.0,3.2
3,2.0,2.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,18.0,22.0,4.9
4,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,99.0,15.0,3.6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
75,0.0,2.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,74.0,22.0,4.7
76,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,22.0,21.0,2.7
77,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,12.0,20.0,3.4
78,1.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,79.0,19.0,1.7
79,2.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,24.0,16.0,1.3

In [13]:
pd.DataFrame(le.fit_transform(y_train) , columns=['Satisfaction_Level'])

    Satisfaction_Level
0                    2
1                    1
2                    2
3                    1
4                    0
..                 ...
75                   1
76                   2
77                   0
78                   1
79                   0

[80 rows x 1 columns]