In [1]:
import pandas as pd
from sklearn.preprocessing import MinMaxScaler

In [3]:
df = pd.read_csv('tested.csv')

In [5]:
df.head(5)

   PassengerId  Survived  Pclass                                          Name  ...   Ticket     Fare  Cabin  Embarked
0          892         0       3                              Kelly, Mr. James  ...   330911   7.8292    NaN         Q
1          893         1       3              Wilkes, Mrs. James (Ellen Needs)  ...   363272   7.0000    NaN         S
2          894         0       2                     Myles, Mr. Thomas Francis  ...   240276   9.6875    NaN         Q
3          895         0       3                              Wirz, Mr. Albert  ...   315154   8.6625    NaN         S
4          896         1       3  Hirvonen, Mrs. Alexander (Helga E Lindqvist)  ...  3101298  12.2875    NaN         S

[5 rows x 12 columns]

In [12]:
df[['Fare']].info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 1 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Fare    417 non-null    float64
dtypes: float64(1)
memory usage: 3.4 KB

In [13]:
mm = MinMaxScaler()

In [15]:
x = mm.fit_transform(df[['Fare']])

In [21]:
data = pd.DataFrame(x)

In [22]:
data

            0
0    0.015282
1    0.013663
2    0.018909
3    0.016908
4    0.023984
..        ...
413  0.015713
414  0.212559
415  0.014151
416  0.015713
417  0.043640

[418 rows x 1 columns]